### ISSUE TITLE
PDF417 barcode scanning not supported on Android

### ISSUE THREAD

**Issue by piocyc** [Telerik-Verified-Plugins/BarcodeScanner#11]
I have tested demo application on Android and noticed that PDF417 (https://en.wikipedia.org/wiki/PDF417) barcode format cannot be scanned. Is that intended? Documentation states that PDF417 is supported on Android.

**Comment by EddyVerbruggen** [comment]
Hey @piocyc, I found this issue reported 7 times in the upstream repository as well, but it was unfortunately never addressed.

So I took a look and found an elegant way to add support without breaking anything. I'm not enabling scanning PDF417 by default because that may have implications (clash with other types, false positives, who knows what), but if you update to the 1.2.11 version you'll be able to pass in a `formats` option, which is a comma separated list (no spaces!) of scannable barcodes. For an example see the readme.
