### ISSUE TITLE
Suggestion for future development

### ISSUE THREAD

**Issue by rdlauer** [Telerik-Verified-Plugins/BarcodeScanner#12]
An AppBuilder customer left some feedback that we should consider for a future iteration:

1) Continuous scanning: the scanner will not stop after each successful finding. Instead the camera will stay open and the API continuously return codes. In other words: I can scan many codes at once.

2) Embedded scanner: Currently, the scanner (camera) takes the whole screen. I have seen other scanners that leave a frame around the camera where I can print short messages while I am scanning (e.g. print the 5 last codes or whatever).

**Comment by dandrayan** [comment]
I would love this functionality as well!

**Comment by EddyVerbruggen** [comment]
Hey @dandrayan, do you refer to 1, 2 or both? Just curious to learn which would add the most value to our users. Thanks!

**Comment by dandrayan** [comment]
@EddyVerbruggen Both! I have a project that could benefit from continuous scanning which would display the last few scans. In our case, we need three different types of barcodes scanned to submit an action, so a callback for every scan would be ideal to perform validation. Once we determine that we have the three types of barcodes (order is not important), I would ideally call a method to end the continuous scanning so that I can perform the submission and provide feedback to the user on the submission.

**Comment by Stefan74** [comment]
Hello ... I need an option to scan inverted barcodes (white on black) ... Would be great if that is considered ... Thanks! (Sorry, for my bad english)
![datamatrix_inverted_white_on_black](https://cloud.githubusercontent.com/assets/17643187/13527529/dced5200-e20f-11e5-987b-1b816b2f3107.png)
